# Generated by Django 5.2.12 on 2026-06-06 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Quotation Received', 'Quotation Received'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('PO Generated', 'PO Generated')], default='Draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Sent', 'Sent'), ('Completed', 'Completed')], default='Created', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Generated', 'Generated'), ('Paid', 'Paid')], default='Draft', max_length=50)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='procurement.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_days', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Updated', 'Updated'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Submitted', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='procurement.rfq')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='selected_quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='procurement.quotation'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rfq',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='procurement.rfq'),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=50)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='procurement.rfq')),
            ],
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('specification', models.TextField()),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.rfq')),
            ],
        ),
    ]
